name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permisos a Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar proyecto
        run: ./mvnw clean package -DskipTests

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: sistema-empleados-app-monolitica:latest
